C-Accel-CRIPT/Python-SDK

- .github/pull_request_template.md
- .github/workflows/install.yml
- CONTRIBUTORS.md
- LICENSE
- README.md
- setup.cfg
Add necessary info before setting repo to public.
Added license and contributors file to repo.
Not added: license info for every file yet.
Please double check the legal implications @Ardi028
> Prepare repo to go public

- src/cript/__init__.py
- src/cript/api/exceptions.py
- src/cript/exceptions.py
- src/cript/nodes/exceptions.py
Introduce a common Exception class for all CRIPT exceptions
> make a common base exception for CRIPT

- src/cript/nodes/core.py
- src/cript/nodes/exceptions.py
- tests/test_node_util.py
- tests/test_nodes_no_host.py
For now, we do not allow cycles in the data graphs.
Validation of nodes checks if it creates a cycle in the data graph.
It is not clear if we really want no cycles in our data graph.
I also decluttered the tests to separate node tests from node util tests.
> Implement a cycle prevention

- .github/workflows/docs.yaml
- .github/workflows/docs_build_and_deploy.yaml
Build mkdocs from `main` branch and push to `gh-pages` to be deployed to github pages automatically from there
added `docsyaml`
> created docs CI/CD

- .gitignore
- requirements_dev.txt
adding coverage files and output to .gitignore file
* added coverage file and output html directory to .gitignore
* added coverage.py to requirements_dev.txt
> updated .gitignore to ignore coverage.py

- src/cript/__init__.py
- src/cript/nodes/__init__.py
- src/cript/nodes/exceptions.py
- src/cript/nodes/primary_nodes/inventory.py
- src/cript/nodes/primary_nodes/project.py
- src/cript/nodes/util.py
- tests/fixtures/primary_nodes.py
- tests/test_node_util.py
Validate project nodes, that they don't contain orphan nodes that should be listed in project or experiment.
Extra validation of project graphs.
Added tests to ensure logic is working.
Fixes an additional issue of `inventory` by renaming `materials_list` to `materials`.
It prevented deep copies and json deserialization.
Added a helper function that allows users to easily fix their graphs.
> Check for orphraned nodes

- docs/faq.md
Added more documentation to our FAQ page
added questions for:
* where can I ask questions
* encouraging users to use the discussion tab to read and write questions and answers to increase the community and have users learn from each other.
* Wrote about developers accessing the developer documentation for contribution and creating their own plugins
* fixed the section that was broken with the exceptions
> added more documentation to our FAQ section

- .github/workflows/tests.yml
- .github/workflows/trunk.yml
updating workflow so that it runs on all PR, so we can see if something is failing if we are merging one unprotected branch to another
* changed tests workflow
* trunk workflow
> updated tests and trunk workflow

- docs/api/controlled_vocabulary_categories.md
- docs/api/search_modes.md
- mkdocs.yml
- src/cript/api/vocabulary_categories.py
added documentation for Controlled Vocabulary Categories and how to use them
> added documentation for vocabulary categories

- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/docs.yaml
- .github/workflows/docs_check.yaml
- .github/workflows/test_coverage.yaml
- .github/workflows/tests.yml
- .github/workflows/trunk.yml
- .trunk/trunk.yaml
Setting the actions up for the merge queue of trunk.
A few changes to when CI tests are run.
If we add new tests, we should not forget to add them as required for the merge Q.
> setup merge-q actions

- src/cript/api/api.py
- src/cript/nodes/core.py
- src/cript/nodes/supporting_nodes/file.py
This postpones the file upload until the save of the project.
I think that is a little more in sync with the user expectation.
Also post pone s3 client init and pretreat token.
This helps with the test.
(Before there were situations, where you commented the init of the s3 client out to get the tests passing.)
Now tests should pass, but the client still gets initiated if needed.
None, yet.
> postpone file update until project save

- .github/workflows/tests.yml
- .trunk/configs/.cspell.json
- src/cript/api/api.py
- src/cript/api/paginator.py
- src/cript/api/utils/save_helper.py
- src/cript/nodes/core.py
- src/cript/nodes/subobjects/ingredient.py
- src/cript/nodes/subobjects/quantity.py
- src/cript/nodes/util/__init__.py
- src/cript/nodes/uuid_base.py
- tests/conftest.py
- tests/fixtures/primary_nodes.py
- tests/fixtures/subobjects.py
- tests/nodes/primary_nodes/test_inventory.py
- tests/nodes/primary_nodes/test_material.py
- tests/nodes/primary_nodes/test_process.py
- tests/test_integration.py
> Bad UUID handling

- docs/faq.md
simply wrote an MD section about how to the CRIPT Python SDK team. Added another section about where users can message us about security issues.
> Update Documentation FAQ.md

- .trunk/configs/.cspell.json
- docs/examples/.gitignore
- docs/examples/simulation.md
- docs/examples/synthesis.md
- mkdocs.yml
Add an example for a simulation data graph with the Python SDK.
Add an example
Not yet added.
There is an issue with saving files. @nh916 can you take a look and make it right?
> add simulation example notebook

- src/cript/api/api.py
- src/cript/api/utils/save_helper.py
> Refactor the save a little bit. Patch does not work.

- src/cript/nodes/primary_nodes/collection.py
- src/cript/nodes/primary_nodes/computation.py
- src/cript/nodes/primary_nodes/computation_process.py
- src/cript/nodes/primary_nodes/data.py
- src/cript/nodes/primary_nodes/experiment.py
- src/cript/nodes/primary_nodes/inventory.py
- src/cript/nodes/primary_nodes/material.py
- src/cript/nodes/primary_nodes/process.py
- src/cript/nodes/primary_nodes/project.py
- src/cript/nodes/primary_nodes/reference.py
- src/cript/nodes/subobjects/equipment.py
- src/cript/nodes/subobjects/ingredient.py
- src/cript/nodes/subobjects/parameter.py
- src/cript/nodes/subobjects/property.py
- src/cript/nodes/subobjects/quantity.py
- src/cript/nodes/subobjects/software.py
- src/cript/nodes/subobjects/software_configuration.py
Added JSON representation of every node within its documentation page. I think this helps a lot to understand what the code under the hood is doing and helps the user understand and work with the software better.
* Add a block of JSON representation code to every node documentation page.
* formatted the process node table
* fixed broken links within data.py
* formatted the table as well
* The JSON has to be updated manually every time something changes
* Some of the JSON can be better picked to easier demonstrate how the code works to the user
* However, what it has currently I think helps a lot too
<details>
<summary>click to view the screenshots</summary>
</details>
> added JSON representation to all nodes in documentation

- tests/api/test_api.py
`test_api_delete_material` tests from tests/api/test_api.py
wrote these tests earlier, but I don't think they'll be needed
> removed unneeded tests from test_api.py

- src/cript/api/api.py
- src/cript/api/exceptions.py
- src/cript/api/utils/save_helper.py
- src/cript/nodes/core.py
- tests/fixtures/subobjects.py
- tests/nodes/primary_nodes/test_collection.py
- tests/nodes/primary_nodes/test_computation.py
- tests/nodes/primary_nodes/test_computational_process.py
- tests/nodes/primary_nodes/test_data.py
- tests/nodes/primary_nodes/test_experiment.py
- tests/nodes/primary_nodes/test_inventory.py
- tests/nodes/primary_nodes/test_material.py
- tests/nodes/primary_nodes/test_process.py
- tests/nodes/primary_nodes/test_project.py
- tests/nodes/primary_nodes/test_reference.py
- tests/nodes/subobjects/test_algorithm.py
- tests/nodes/subobjects/test_citation.py
- tests/nodes/subobjects/test_computational_forcefiled.py
- tests/nodes/subobjects/test_condition.py
- tests/nodes/subobjects/test_equipment.py
- tests/nodes/subobjects/test_ingredient.py
- tests/nodes/subobjects/test_parameter.py
- tests/nodes/subobjects/test_property.py
- tests/nodes/subobjects/test_quantity.py
- tests/nodes/subobjects/test_software.py
- tests/nodes/subobjects/test_software_configuration.py
- tests/nodes/supporting_nodes/test_file.py
- tests/test_integration.py
Integration tests for update functionality
within each node's test file, the `test_integration...` handles that node's create and update
* after create is done within the integration tests, then I change a small attribute on the desired node, to trigger an update
* In most places I've tried putting `"UPDATE"` within the changed attribute, but for some I could not do that
* changed print statements formatting to make it easier to see and not get lost within the terminal outputs
* All the create tests passed fine and I added a a little separator, and then the update tests run after create tests separator is:
```
######################################## TEST Passed ########################################
```
* The code for comparing the JSONs is not perfect, because I have noticed a couple …
> Integration Tests for Update/PATCH

- docs/tutorial/how_to_get_api_token.md
> Fix docs image

- CONTRIBUTING.md
I was submitting a PR for an open source project that I like last night and saw that their CONTRIBUTING.md had a lot of great resources, so I wanted to quickly add those to our repository as well.
* wrote about 
* `How to Contribute`
*  `Issue Submission Guidelines` 
*  `PR Submission Gudelines`
* added code of conduct link to CONTRIBUTING.md
> upgraded repository CONTRIBUTING.md

- requirements.txt
- requirements_dev.txt
- requirements_docs.txt
IDE found some outdated packages, so updating them here
I saw that `pytest` package was missing from `requirements_dev.txt` and added it
* passing tests exactly the same and there is no issue for us
> updated outdated packages

- src/cript/api/valid_search_modes.py
added type hints to the search modes enum
> added type hints to the search modes enum

- docs/examples/synthesis.md
- docs/tutorial/how_to_get_api_token.md
- src/cript/api/api.py
wrote section on token security within `how to get API token tutorial` and `API client class page`
* wrote section on token security within `how to get API token tutorial` and `API client class page`
* wrote sections on creating API with env vars, `None`
* fixed empty link
<details>
<summary> click to see screenshots </summary>
</details>
* The UI and UX are not great
* This provides us a jumping off point for us to iterate and make it better
> Docs token security

- .github/workflows/docs_check.yaml
removed extra duplicate step at the end
> removed extra duplicate step at the end

- src/cript/nodes/subobjects/property.py
found a broken link and fixed it
> fixed broken link in docs

- docs/tutorial/cript_installation_guide.md
- src/cript/api/api.py
- src/cript/api/paginator.py
wrote missing docs for paginator and added a way for to install the SDK from Git.
<details>
<summary>click to see screenshots</summary>
</details>
> wrote missing docs for paginator and added a way for to install the SDK from Git.

- src/cript/nodes/subobjects/quantity.py
> fix quantity type

- src/cript/api/api.py
- src/cript/nodes/util/__init__.py
- tests/api/test_api.py
- tests/test_integration.py
This now fails a bunch of tests.
(Feel free to add the `skip` to pytest.
I don't know how to do that.
More importantly, when locally run it shows all the issues of the back end.
> fix the deep diff comparison.

- src/cript/api/api.py
made the documentation a bit less technical and more user friendly. Upgraded UI to be a bit easier to read, improving the UX
> upgrade `cript.API.download_file()` docs

- .github/workflows/test_coverage.yaml
- .github/workflows/tests.yml
- tests/conftest.py
Integration test switch gets its value from env vars and workflow has been updated too
> Integration Test Switch, gets value from env var

- .github/workflows/test_examples.yml
- requirements.txt
- requirements_dev.txt
- requirements_docs.txt
updating requirements and putting `jupytext` into `requirements_docs.txt` because it is only used within documentation
> updating requirements and putting `jupytext` into `requirements_docs.txt`

- .github/workflows/test_coverage.yaml
- .github/workflows/test_examples.yml
- .github/workflows/tests.yml
- tests/conftest.py
changed conftest.py to get storage token from env variable
> changed conftest.py to get storage token from env variable

- src/cript/nodes/uuid_base.py
> Handle empyt UUID correctly in JSON, by assigning new UUID

- tests/conftest.py
small suggestion for conftest.py
> conftest env var upgrade

- src/cript/nodes/util/__init__.py
Wrote documentation for `load_nodes_from_json` as that will be useful for the user as they are working through the code.
> Wrote documentation for `load_nodes_from_json`

- src/cript/api/api.py
> Add trailing slashes to work with staging

- src/cript/api/api.py
wrote `cript.API.__str__` method
did not write tests for it as I was thinking it would not be needed
> wrote `cript.API.__str__` method

- tests/nodes/primary_nodes/test_computational_process.py
- tests/nodes/primary_nodes/test_data.py
- tests/nodes/primary_nodes/test_process.py
- tests/nodes/subobjects/test_computational_forcefiled.py
- tests/nodes/subobjects/test_software_configuration.py
simplified some tests
* removed `deep_copy` from the tests, making them simpler to understand and work with
> simplified tests

- .trunk/configs/.cspell.json
- tests/api/test_api.py
updated tests to pass for staging
* essentially made a bunch of tests into `or`
* try this if it doesn't work then try this, whichever that succeeds is the winner
* we can also set a `SERVER_INSTANCE = "STAGING"` or some other way of doing it
* integration tests for API should pass besides S3 file upload 
* file upload still not working
* I think because staging has different S3 variables than develop, so the staging token will not work with develop S3 variables
* the way I wrote `API search by UUID test` probably can be cleaned up in the future after ACS
> updated tests for staging

- src/cript/nodes/core.py
- src/cript/nodes/util/__init__.py
Wrote documentation for `NodeEncoder` class
> Wrote documentation for `NodeEncoder` class

- src/cript/nodes/core.py
- src/cript/nodes/primary_nodes/collection.py
- src/cript/nodes/primary_nodes/computation.py
- src/cript/nodes/primary_nodes/process.py
- src/cript/nodes/util/__init__.py
- tests/integration_test_helper.py
- tests/nodes/primary_nodes/test_collection.py
- tests/nodes/primary_nodes/test_computation.py
- tests/nodes/primary_nodes/test_experiment.py
- tests/nodes/primary_nodes/test_process.py
This rehandles the std fields in JSON.
1) it add default fields when they are not sent by the API. This helps to tolerate missing required arguments.
2) default fields are better suppressed when serializing, this helps to reduce false positives during integration testing.
This required to change some default list fields from `None` to list.
> Std args json

- src/cript/api/api.py
wrote documentation explaining api.host
> wrote docs explaining host

- src/cript/nodes/subobjects/algorithm.py
I saw that I missed algorithm type when originally writing documentation examples
> wrote example docs for `algorithm`

- .github/workflows/test_coverage.yaml
- .github/workflows/test_examples.yml
- .github/workflows/tests.yml
changed CI to use staging host instead of develop
> changed CI to use staging host instead of develop

- tests/api/test_api.py
> making `cript.API.search` tests more robust for all environments

- src/cript/api/api.py
- src/cript/api/exceptions.py
- src/cript/api/paginator.py
- src/cript/api/vocabulary_categories.py
- src/cript/nodes/primary_nodes/computation.py
- src/cript/nodes/primary_nodes/computation_process.py
- src/cript/nodes/primary_nodes/data.py
- src/cript/nodes/primary_nodes/material.py
- src/cript/nodes/primary_nodes/process.py
- src/cript/nodes/primary_nodes/reference.py
- src/cript/nodes/subobjects/algorithm.py
- src/cript/nodes/subobjects/citation.py
- src/cript/nodes/subobjects/computational_forcefield.py
- src/cript/nodes/subobjects/condition.py
- src/cript/nodes/subobjects/equipment.py
- src/cript/nodes/subobjects/ingredient.py
- src/cript/nodes/subobjects/parameter.py
- src/cript/nodes/subobjects/property.py
- src/cript/nodes/subobjects/quantity.py
- src/cript/nodes/supporting_nodes/file.py
replacing all vocabulary links to new production server
> replacing all vocabulary links to new production server

- src/cript/api/api.py
> fixing file upload for production AWS S3 server

- docs/examples/simulation.md
- docs/examples/synthesis.md
pointing example code docs to production server instead of develop
> fixing example documentation code last second

- .trunk/configs/.cspell.json
- .trunk/trunk.yaml
- CONTRIBUTING.md
- CONTRIBUTORS.md
- mkdocs.yml
> fix various spelling (and ignore the others)

- .github/workflows/build_and_deploy_docs.yaml
updated documentation CD to deploy when merging to main instead of develop
> Changed Docs CD to deploy when merging to `Main`

- docs/examples/simulation.md
- docs/examples/synthesis.md
- docs/index.md
- docs/tutorial/how_to_get_api_token.md
- src/cript/api/api.py
- src/cript/nodes/primary_nodes/collection.py
- src/cript/nodes/primary_nodes/computation_process.py
- src/cript/nodes/primary_nodes/data.py
- src/cript/nodes/primary_nodes/experiment.py
- src/cript/nodes/primary_nodes/inventory.py
- src/cript/nodes/primary_nodes/material.py
- src/cript/nodes/primary_nodes/process.py
- src/cript/nodes/primary_nodes/project.py
- src/cript/nodes/supporting_nodes/file.py
Upgraded docs
* added notes to attributes table of all primary nodes and file to make reading docs for users easier
* corrected links to point to CRIPT frontend correctly
* updated file node example code, to have `name` attribute
* update file node documentation to not be hidden within expandable widget
* fixed some formatting issues
> Upgraded Docs

- README.md
removed disclaimer from RAEDME.md
> remove disclaimer from README

- README.md
add `CRIPT Availability` to README.md
> add `CRIPT Availability` to README.md

- .trunk/configs/.cspell.json
- src/cript/api/api.py
- src/cript/api/valid_search_modes.py
- tests/api/test_api.py
added bigsmiles search to SDK
* wrote a test for bigsmiles search test
* added `BIGSMILES` to `SearchModes` enum for easy searching
* added bigsmiles searchmode to API endpoint
* wrote a lot of documentation regarding all search modes
> look how beautiful that is! 😍🤩😍
* I noticed a couple of times that the nodes coming back were in different orders
* The bigsmiles search takes a while to run on the API side
* The test is not very rigorous in case we need to use it between different servers with different data in their DB
> Feature: add bigsmiles search to SDK

- requirements.txt
- requirements_dev.txt
- requirements_docs.txt
upgraded outdated requirement packages
> upgraded requirements

- src/cript/api/api.py
- tests/api/test_api.py
created a `BIG Project node` that has 100+ nodes in it for testing
The code is written in a NOT DRY way, so later  we will need to do slight refactoring to clean it up, and possibly a helper function that creates all the needed nodes for the `test_api_node_limit` test function. We can do this in our clean up period. I think it will work for now.
> 100+ nodes project for testing

- .trunk/.gitignore
- .trunk/trunk.yaml
- src/cript/api/__init__.py
- src/cript/api/api.py
- src/cript/api/paginator.py
- src/cript/api/utils/web_file_downloader.py
- src/cript/nodes/exceptions.py
- src/cript/nodes/subobjects/ingredient.py
Updating trunk
there are a couple more linters.
The most potent one so far is bandit.
I had to turn of bandit in the `tests` path, because it was detecting out `asserts` and our hard coded dummy passwords.
Ideally, we find a way to turn it back on.
> Trunk upgrade

- src/cript/api/api.py
upgraded the error message/handling for `cript.API.search()`
Gave some more context as to what could be happening for the user and helping the user report it to us, otherwise the user might just report `"got an error in search"`, which will be hard for us to help with and frustrating for them reporting.
Using `else` instead of an `if` to catch all cases not caught by the `if` kind of similar to a switch statement in other languages.
* no tests written for this
* I could write a test for this, but it might be overkill and add to the list of tests that we have to maintain anyways right now
> upgraded the error handling for `cript.API.search`

- src/cript/api/api.py
changed `get_vocab_by_category()` `Exception` to nice `APIError`
> upgraded error for `get_vocab_by_category()`

- requirements.txt
- requirements_docs.txt
- setup.cfg
a few packages were slightly outdated, so I updated them both in `requirements.txt` and `setup.cfg`
> upgraded packages in `requirements.txt` and `setup.cfg`

- requirements.txt
- setup.cfg
downgrade `JSONSchema` package to work with Python 3.7
> downgrade `JSONSchema` package to work with Python 3.7

- src/cript/nodes/primary_nodes/data.py
updated `Data` node constructor `File` creation example
> updated `Data` node constructor `File` creation example

- .github/pull_request_template.md
I've noticed test section has not been used in a while, and is just bloating the PR template lately, so  I'm thinking of removing it
> update PR template to remove the `Test` section

- README.md
I did a lot of work on it and thought it'd be nice to highlight it within the documentation section to not get missed. 
Not sure if I have highlighted it enough and this it too much or if this is good
> added link to wiki documentation to the documentation section of the README

- .github/workflows/build_and_deploy_docs.yaml
- .github/workflows/codeql.yml
- .github/workflows/docs_check.yaml
- .github/workflows/mypy.yaml
- .github/workflows/test_coverage.yaml
- .github/workflows/test_examples.yml
- .github/workflows/tests.yml
- .github/workflows/trunk.yml
upgraded GitHub action version [checkout](https://github.com/actions/checkout/releases) and [setup-python](https://github.com/actions/setup-python/releases) to v4
tested GH actions on [my fork](https://github.com/nh916/Python-SDK/actions)
> upgraded GitHub action version `checkout` and `setup-python` to latest v4

- docs/faq.md
added more sections to FAQ and fixed some spelling errors
* `How can I contribute to this project?` question was too long, so I chopped it into 2 sections instead
* added: `Is there documentation detailing the internal workings of the code?` question
* added the question: `Where can I find the release notes for each SDK version?`
* fixed grammar error in `Besides the user documentation, is there any developer documentation that I can read through on how the code is written to get a better grasp of it?`
> added more sections to FAQ and fixed some grammar errors

- .trunk/trunk.yaml
* upgraded trunk via terminal command `trunk upgrade`
> upgraded trunk

- src/cript/api/api.py
- src/cript/api/utils/aws_s3_utils.py
refactored `get_s3_client` into a function to reduce the bulk of `cript.API` and make it easier to navigate and handle
* removed some bulk from the `cript.API` class
* wrote docstrings for `get_s3_client`
* tested the code and it is working fine
* formatted the whole thing with black
* changed log to have `file` be capitalized for better UI
> refactored `get_s3_client` into a function in a aws_s3_utils.py file

- src/cript/api/api.py
renamed `_api_phandle` to `_api_prefix` because that is the correct term. This will make the code more self documenting and easier to read.
> renamed variable to be more self documenting and correct

- tests/nodes/primary_nodes/test_collection.py
- tests/nodes/primary_nodes/test_computation.py
- tests/nodes/primary_nodes/test_computational_process.py
- tests/nodes/primary_nodes/test_data.py
- tests/nodes/primary_nodes/test_inventory.py
- tests/nodes/primary_nodes/test_material.py
- tests/nodes/primary_nodes/test_process.py
- tests/nodes/primary_nodes/test_project.py
- tests/nodes/supporting_nodes/test_file.py
added notes to creation tests and getter & setter tests to strengthen the tests
* removed some unneeded variables when seen
* removed some unneeded copy when seen
> Upgrade node unit tests

- src/cript/nodes/primary_nodes/data.py
- src/cript/nodes/subobjects/citation.py
- src/cript/nodes/subobjects/computational_forcefield.py
- src/cript/nodes/subobjects/condition.py
- src/cript/nodes/subobjects/equipment.py
- src/cript/nodes/subobjects/ingredient.py
- src/cript/nodes/subobjects/parameter.py
- src/cript/nodes/subobjects/property.py
- src/cript/nodes/subobjects/quantity.py
- src/cript/nodes/supporting_nodes/file.py
Added controlled vocab links to documentation for each node attribute
> Added controlled vocab links to documentation for each node attribute

- src/cript/api/paginator.py
Changed Paginator error message to be better and easier for the user to debug
```shell
cript.api.exceptions.APIError: CRIPT Python SDK sent HTTP `GET` request to URL: `https://api.criptapp.org/api/v1/search/exact/reference/?q=10.1021/ma030322y&page=0` and API responded with <Response [400]>
```
```shell
cript.api.exceptions.APIError: CRIPT Python SDK sent HTTP `GET` request to URL: `https://api.criptapp.org/api/v1/search/exact/reference/?q=10.1021/ma030322y&page=0` and API responded with {'code': 400, 'data': None, 'error': 'Unknown auth provider'}
```
The script I was using to do the test
```python
import json
import os
import cript
api_token = os.environ.get('CRIPT_API_TOKEN')
storage_token = os.environ.get('CRIPT_STORAGE_TOKEN')
api = cript.API(
host='https://api.criptapp.org', …
```
> improve paginator error message

- src/cript/api/api.py
wrote docs for `_prepare_host` so it is clearer for future maintenance
* wrote docs for `_prepare_host` so it is clearer for future maintenance
> wrote missing docs for a method

- src/cript/api/api.py
updated docs: added notes that pathlib is recommended to work with file paths #378
> updated docs: added notes that `pathlib` is recommended to work with file paths

- src/cript/api/api.py
- src/cript/api/exceptions.py
- src/cript/api/paginator.py
- src/cript/nodes/primary_nodes/computation_process.py
- src/cript/nodes/primary_nodes/data.py
- src/cript/nodes/primary_nodes/process.py
- src/cript/nodes/supporting_nodes/file.py
- tests/fixtures/subobjects.py
- tests/nodes/primary_nodes/test_process.py
finished off some TODO comments and removed TODO comments of already finished work
* removed already finished TODO comments
* upgraded `test_complex_process_node` to use fixture, removed unused fixtures, and removed copy.deep_copy()
> Finished and Removed TODO

- .github/workflows/doctest.yaml
cleaned up doctest.yaml CI file of the `pwd` that was mistakenly left in there
> cleaned up doctest.yaml CI file

- src/cript/api/api.py
Fixed issue with heading and host example error
fixed issue with heading and bad host example
> fixed docs heading `Create API Client with Environment Variables`

- .github/pull_request_template.md
added a checklist item to PR template to remind developers to write automated tests for the code changes
> added new checklist item to PR template about `automated tests`

- .trunk/configs/.cspell.json
- src/cript/nodes/core.py
- tests/test_node_util.py
built on @InnocentBug [work](https://github.com/C-Accel-CRIPT/Python-SDK/pull/412), same logic just with full docs and better variable names
* wrote full docs with doctest code example
* added type hinting to the function
* added example JSON
* changed the name `get_self_contained_json` because it is not very self documenting and does not fully convey the function's functionality to `get_expanded_json`.
* renamed test function
* renamed variables within the test function
* added docstrings to test function
* the docstrings are a bit long, but I think it is completly worth it because it becomes super clear as to what this code is doing.
> Json file format additions

- src/cript/nodes/core.py
- tests/test_node_util.py
Saw a couple of places that I could quickly and easily refactor our code for readability, improve docs, and fix a small syntax error and quickly made the changes and sent it here
> fixed some small errors and mostly improved the code and docs

- src/cript/nodes/primary_nodes/project.py
Hot fix that allows you to save projects again.
> fix overloaded validate

- setup.cfg
> upgraded version from 2.1.0 to 2.2.0

- setup.cfg
- src/cript/nodes/primary_nodes/project.py
bumped SDK version from 2.1.0 to 2.2.0
> bumped SDK version from 2.1.0 to 2.2.0

- src/cript/api/data_schema.py
> Fix message disabling tests

- src/cript/nodes/core.py
Minimal change, but removes the `uuid` field from the top-level node in a patch call.
> Add a working patch option for `get_json`
