README.md
Fixed typo for badges: 
* `Dependencies: JSONSchema`
* `Dependencies: Requests`
* `Dependencies: mypy`
=> fixed typo for `Dependencies: JSONSchema`

.github/workflows/dependency-review.yml
Dependency security scanning. This could be a good security tool to scan any issues with the packages that we are using. This would ensure that our package is secure because even if our code is secure, but we are using a package or package version that is unsecure then it would create security vulnerabilities within our package.
This workflow comes directly from GitHub and is not by a third party
=> Create CI/CD of dependency security scanner

tests/api/test_api.py
API test `test_get_db_schema_from_api` was failing previously on other PR because the fields on the db schema has been updated from `69` to `70` fields. This PR reflects the latest updates in the API tests
=> updatied db schema test to after db schema was updated

requirements.txt, requirements_dev.txt, requirements_docs.txt
updated outdated packages. 
`pymdown-extensions` version 9 has vulnerabilities that can be fixed by updating to v10
* tests are all still passing except for the db schema test that expects 70 fields but is getting 74 fields
=> updated packages

.github/workflows/docs_check.yaml
This would be a great workflow check to have for mass refactoring and changes such as [Computation Process PR](https://github.com/C-Accel-CRIPT/Python-SDK/pull/123), that could catch any errors with documentation quickly and easily.
**Issue Link:** https://github.com/C-Accel-CRIPT/Python-SDK/issues/129
* created docs_check.yaml
* tested this CI on a [forked repository](https://github.com/nh916/Python-SDK-tests)
* None
I was not sure if I should set it as strict or not. I set it as strict once and ran it and it reported harmless warnings as errors that need attention, so I removed it because I think it is fine not being strict for now
```yaml
- name: Build and Test Documentation
run: |
mkdocs build
mkdocs build --strict
```
I think the next step that could be even better is that if …
=> created docs_ci_check

src/cript/api/api.py, src/cript/nodes/supporting_nodes/file.py, tests/nodes/supporting_nodes/test_file.py
* wrote `_file_source_setter` with typehints and docstrings
* this is not my favorite design because it is essentially a setter for the setter, but since both constructor and setter check node schema and the file node might not be valid yet because everything has not been set yet, it might create an issue
* this avoids duplicate code for both setter and constructor, but it is not the best
* Since Python says whatever that can be a function should be a function, I wrote `_file_source_setter`  as a function
* since it does not refer to self it can easily be made into a function for easy refactoring if needed.
* updated docs for file source in constructor
> Note: File constructor is longer than expected. Some of it can later be cut down to be more concise with user testing or just review
* …
=> Feature: `File.upload()` & `File.download()`

.github/workflows/test_coverage.yaml, requirements_dev.txt
Added CI to keep track of how much of the code our tests are covering. Test coverage is important because it helps to ensure that all of the code is tested, and that any bugs are caught early. We can have a million tests, but if we are not covering a large portion of the code then the tests are useless.
* Added [pytest coverage](https://pytest-cov.readthedocs.io/en/latest/) to `requirements_dev.txt` for CI 
* we already have [coverage.py](https://coverage.readthedocs.io/en/7.2.7/) and it works well and shows the coverage well in terminal locally, it is nice for local checking
* I am okay with keeping or removing it, I can see a case for both ways
* Wrote GitHub workflow CI to check code coverage on every push, pull_request, and can be triggered manually if needed
* set it to 90% coverage …
=> Created Test coverage CI

.github/workflows/dependency-review.yml, .trunk/trunk.yaml
It seems like that the dependency test doesn't like to run on wild card branch pushes.
But these are required for the trunk merge q
Removed the test to run on trunk merge q and remove it from requirements.
Tested on fork. The merge q works.
The tests still run on PRs and pushes, it just doesn't prevent merging with the Q.
Trunk Merge Q doesn't work on forked repos. But we can still merge manually and sholdn't be a big deal.
- [ x] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.
=> Removing the faulty test from merge q

src/cript/nodes/core.py, src/cript/nodes/primary_nodes/collection.py, src/cript/nodes/primary_nodes/project.py, tests/nodes/primary_nodes/test_collection.py
With the removal of the group node, we also need to add the `member` and `admin` to collections.
A few changes to the expected data types of project, that I overlooked.
added a check in the serialization test
Docs not updated.
=> add member and admin to collection

src/cript/nodes/core.py, src/cript/nodes/primary_nodes/primary_base_node.py, src/cript/nodes/subobjects/algorithm.py, src/cript/nodes/subobjects/citation.py, src/cript/nodes/subobjects/computational_forcefield.py, src/cript/nodes/subobjects/condition.py, src/cript/nodes/subobjects/equipment.py, src/cript/nodes/subobjects/ingredient.py, src/cript/nodes/subobjects/parameter.py, src/cript/nodes/subobjects/property.py, src/cript/nodes/subobjects/quantity.py, src/cript/nodes/supporting_nodes/user.py, src/cript/nodes/uuid_base.py
According to @brili all nodes (including subobjects) have a UUID, and a few other attributes.
So, I added those attributes to the UUIDBaseNode and have all nodes inherit from it.
This might be better done with refactoring, and considering how BaseNode and UUIDBaseNode now serve a similar function.
Documentation isn't up to date with this.
=> UUID base all

src/cript/nodes/primary_nodes/material.py, tests/conftest.py, tests/fixtures/primary_nodes.py, tests/nodes/primary_nodes/test_material.py, tests/test_node_util.py
Process is again part of the material node.
I think it used to be an array, now it is a single value.
Testing this like ususal.
None
Not sure about documentation, the old one with the process was still in.
=> add process back into material

.trunk/configs/.cspell.json, requirements.txt, requirements_dev.txt, setup.cfg, src/cript/api/api.py, src/cript/api/paginator.py, src/cript/nodes/primary_nodes/collection.py, src/cript/nodes/primary_nodes/computation_process.py, src/cript/nodes/primary_nodes/data.py, src/cript/nodes/primary_nodes/experiment.py, src/cript/nodes/primary_nodes/inventory.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/primary_base_node.py, src/cript/nodes/primary_nodes/process.py, src/cript/nodes/primary_nodes/project.py, src/cript/nodes/primary_nodes/reference.py, src/cript/nodes/subobjects/citation.py, src/cript/nodes/subobjects/computational_forcefield.py, src/cript/nodes/subobjects/condition.py, src/cript/nodes/subobjects/equipment.py, src/cript/nodes/subobjects/ingredient.py, src/cript/nodes/subobjects/parameter.py, src/cript/nodes/subobjects/property.py, src/cript/nodes/subobjects/quantity.py, src/cript/nodes/subobjects/software.py, src/cript/nodes/subobjects/software_configuration.py, src/cript/nodes/supporting_nodes/file.py, src/cript/nodes/supporting_nodes/user.py
I noticed that within [fix_mypy_types branch](https://github.com/C-Accel-CRIPT/Python-SDK/tree/fix_mypy_types) there was some `@beartype` but some not, so I left the ones that were in there and created a separate branch to put 
added [@beartype](https://github.com/beartype/beartype) to all the nodes and merge them back into [fix_mypy_types branch](https://github.com/C-Accel-CRIPT/Python-SDK/tree/fix_mypy_types)
* added [@beartype](https://github.com/beartype/beartype) to all the nodes that were missing it
* there is probably some functions/methods within nodes that this is missing
* I'm thinking it's not crucial for v1 if it is missing in a couple of places, but if we can catch all of them then all the better
=> Add beartype check

.github/workflows/mypy_check.yaml
Added [mypy](https://mypy.readthedocs.io/en/stable/) static type checker for our code. This is just one more layer of protection that we could have to possibly catch errors as we go.
* created `mypy_check.yaml`
* I am running this only on ubuntu with both python version `3.7` and `3.11` only
* I thinking this is pretty minimal, but I would be open to adding more OS and Python versions or only using a single OS and 1 Python version
* running it on every push and pull_request
* tested it on a [forked repository](https://github.com/nh916/Python-SDK-tests/actions/workflows/mypy_check.yaml)
* a lot of our current code is not passing it, and not sure if we need to start optimizing for this yet and checking it
* but it might be nice to just have just in case and we can check the report and catch …
=> Create mypy_check.yaml CI

src/cript/nodes/supporting_nodes/file.py, tests/fixtures/supporting_nodes.py, tests/nodes/primary_nodes/test_computational_process.py, tests/nodes/primary_nodes/test_data.py, tests/nodes/primary_nodes/test_experiment.py, tests/nodes/supporting_nodes/test_file.py
since [File node inherits from base attributes in the data model](https://pubs.acs.org/doi/suppl/10.1021/acscentsci.3c00011/suppl_file/oc3c00011_si_001.pdf#page=28), I fixed that within the SDK File node and inherited all `PrimaryBaseNode` attributes
* removed unused `file_node` fixture within `test_files.py`
* class and data class inheriting from the correct `PrimaryBaseNode`
* tests are all passing for file nodes and fixture inheriting from `PrimaryBaseNode`
* None
=> file node inheriting from PrimaryBaseNode.py

src/cript/api/api.py
Noticed I missed some type hints when I originally wrote it, so I quickly added them here. Was not sure how to type hint this line so I left it as is for now, but both should be type `str`
```python
file_name, file_extension = os.path.splitext(os.path.basename(file_path))
```
* added type hinting to `cript.API.upload_file()`
* fixed grammar of comment
=> Add type hints to `cript.API.upload_file()`

src/cript/nodes/primary_nodes/material.py, tests/nodes/primary_nodes/test_material.py
Removing unneeded and unused material keyword validation and material identifier validation. 
We are using the db schema for the vocabulary validation, so these methods no longer make sense to be here. 
Originally When I made it I thought we were going to check it manually so I wrote a loop and double for loop to check if the vocabulary existed within the controlled vocabulary, and thankfully that can now be optimized.
* removed `_validate_keyword` in materials,py
* removed `_validate_identifiers` in materials.py
* removed `_validate_keyword` from constructor and keywords setter
* formatted the attributes table in the class docstrings
=> Remove material identifier keyword validations

mkdocs.yml
Add example walkthrough to navigation within the SDK documentation
* changed MKDocs.yaml to include the files
* added a dedicated section for example code walkthroughs
<details>
<summary>See Screenshots</summary>
</select>
</details>
=> Add example walkthrough to navigation within the SDK documentation

tests/api/test_api.py
Integration tests have been commented out to pass GitHub actions tests, but can go unnoticed to developers when pulling and testing locally. @InnocentBug gave the good idea of writing warnings for the tests that need to be uncommented, and I have written comments for all for the [integration tests](https://github.com/C-Accel-CRIPT/Python-SDK/pull/168) and for the API tests since those need an API to work with it
* added warnings to commented out API tests
=> added warning for integration tests for API

.trunk/configs/.cspell.json, src/cript/nodes/supporting_nodes/file.py, tests/api/test_api.py, tests/nodes/supporting_nodes/test_file.py
updated _is_local_file to handle file source URL links and S3 object_name
created a good test for it with good test cases
* within `_is_local_file` I am checking if the file exists on the file path specified, and if it does, then it is a local file, otherwise it is a S3 object_name
* checking if the file_source starts with `http` first because that is an easy check that can speed up the test and make it more accurate
* noticed that the docstrings are in Google style so switched them to numpy style, I think that is the only one that was like that
* renamed `test_upload_and_download_local_file` and updated docstrings to avoid confusion as to what kind of upload it is doing
* > this is unrelated to this PR, but it is a very small change and didn't want to make a new PR for it
* HTTP URL
* …
=> updated _is_local_file to handle `URL`, `AWS S3 object_name`, `absolute file path`, `relative file path`

src/cript/api/api.py, src/cript/api/utils/web_file_downloader.py, tests/api/test_api.py
In the past the SDK could only download files from AWS S3 cloud storage, but now it has the rough ability to download files from URL as well.
* if the URL needs JS enabled, needs sessions, has extra needs, then the downloader throws an error
* the error needs to be tested to be sure that it is user friendly
* refactoring needed: https://trello.com/c/qLaN2hqR
=> Feature: Download `file.source` that is URL

src/cript/api/api.py, src/cript/nodes/supporting_nodes/file.py, tests/api/test_api.py
before `cript.API.download_file()` had `object_name` as parameter, which made sense because it could only download files from AWS S3, but since it can work with file URLs as well then that no longer makes sense. Changed the parameter name to `file_source`
=> renamed the parameter for `cript.API.download_file` from `object_name` to `file_source`

src/cript/api/api.py
wrote documentation for `cript.API.download_file()` and explained fully how it functions.
=> wrote documentation for `download_file`

src/cript/nodes/supporting_nodes/file.py
refactored `cript.File.download()` to get the file name from the node itself instead of asking the user for it
* `cript.File.download()` gets the file name from the node itself instead of asking for it in the method
* the file extension str is manipulated to be uniform and work correctly regardless of how it was inputted
=> `cript.File.download()` gets the file name from the node name

.github/workflows/tests.yml
refactoring tests.yaml
* putting environment variables within `env` block
* changing steps name to make them more obvious
* installing `requirements_dev.txt` in one step and pytest is a part of `requirements_dev.txt`
* `requirements_dev.txt` now has `pytest` inside of it
* running tests with a single command
* spacing out the steps to make it clearer and more readable
* giving the option for tests to be ran manually if desired
tested it on a forked repository
[forked repository tests action results](https://github.com/nh916/Python-SDK-tests/actions/workflows/tests.yml)
=> upgrading tests.yml

tests/conftest.py
import all fixtures in primary, subobject, and supporting nodes. This way it is imported automatically instead of being imported one at a time and if we make a new fixture, we don't have to remember to import it into conftest.py, as it will automatically get imported in
* importing fixtures in with wildcard instead of one at a time
* tested a few nodes to be sure there is no fixture or path error and they worked fine
=> Upgrade: Importing Fixtures Automatically into conftest.py

src/cript/api/api.py, src/cript/nodes/supporting_nodes/file.py, tests/api/test_api.py, tests/fixtures/primary_nodes.py, tests/fixtures/subobjects.py, tests/nodes/subobjects/test_algorithm.py, tests/nodes/subobjects/test_parameter.py, tests/nodes/subobjects/test_software_configuration.py, tests/test_node_util.py
Knocked out a few small TODO that was left. Not a huge improvement to the project, but helps knock out some things that we've been putting aside
* changing TODO comment with `pytest.skip`
* changed checking db schema length in test_api.py
* instead of checking if the db schema is the exact same length, I am checking if it has more than `30` fields
* > db schema is always changing so this test will break often, but it should have more than `30` fields because there are at least `24` nodes
* renamed `complex_algorithm_node` to `simple_algorithm_node`
* because it was minimalistic and not maximal node with all required arguments
*  made changes across all the tests that were using it
* changed `simple_property_node` fixture to named arguments, and added docstrings to it
* cleaned up …
=> Knocking out `TODO` comments where possible

src/cript/nodes/util/__init__.py, tests/nodes/test_utils.py
this function was missing a test case and since I am thinking of refactoring it soon, test cases would be really helpful with that and being sure that the project works well anyways
* wrote test function and test cases for `_is_node_field_valid()`
* made a change that if the field is a list, but the string inside is empty then it is invalid
=> wrote test function for `_is_node_field_valid()`

docs/examples/simulation.md, docs/examples/synthesis.md, docs/index.md, src/cript/nodes/primary_nodes/collection.py, src/cript/nodes/primary_nodes/experiment.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/process.py, src/cript/nodes/primary_nodes/project.py
Fixed Broken links found within the documentation
* found and fixed broken links
* formatted attribution tables
* removed last section from home page of documentation because there was nothing for me to replace it with currently
Wrote a [wiki section on discovering and fixing broken links within the documentation](https://github.com/C-Accel-CRIPT/Python-SDK/wiki/Documentation#fixing-broken-links). This strategy works for now, however, ideally, we'd want to check all broken links in CI and get a notification as soon as something breaks for us to fix, so there will never be a broken link in the documentation pages
=> Fix documentation broken links

.trunk/configs/.cspell.json, src/cript/api/api.py
Putting in a log statement in the package to show that the program is working in the background as the user is waiting for it to load.
* wrote an INFO log statement to show things are happening in the background and it is not just standing still
* wrote an option to turn off the log statements if you don't want to see them
* using the variable name of `verbose` because it is standard and well known that it is responsible for terminal logs
=> UX: Node Validation Output

.trunk/.gitignore, .trunk/configs/svgo.config.js, .trunk/trunk.yaml, trunk
Updating trunk and its linters.
=> trunk update

src/cript/api/api.py, src/cript/api/utils/__init__.py, src/cript/api/utils/helper_functions.py
refactoring `cript.API._is_node_schema_valid`
taking the getting of node type from JSON and putting it into its own function that can be easily called and make the code cleaner
=> code clean up: `cript.API._is_node_schema_valid` getting node type from utility function

src/cript/api/api.py
found a print statement that was left in from development and was unintentionally printing to terminal
=> removing print statement from `cript.API.search()`

tests/api/test_api.py, tests/conftest.py, tests/nodes/supporting_nodes/test_file.py, tests/nodes/supporting_nodes/test_user.py, tests/test_integration.py
Test integration works much easier now and can be switched ON/OFF with a boolean and any test that is skipped is marked transparently in the output
so now if we want to run integration tests we can easily switch `HAS_INTEGRATION_TESTS_ENABLED=False` to True and we are done
* added ON/OFF boolean variable in conftest.py to easily switch them ON/OFF
* added if statement to skip integration tests to make skipping them easy and transparent
* added skip decorator to unused file tests to make skipping them transparent
* uncommented a file test that works well currently
* cleaned up `test_user.py`
=> Tests integration with `ON/OFF` switch

mkdocs.yml, src/cript/nodes/primary_nodes/computation.py, src/cript/nodes/primary_nodes/computation_process.py, src/cript/nodes/primary_nodes/data.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/process.py, src/cript/nodes/primary_nodes/reference.py, src/cript/nodes/subobjects/algorithm.py, src/cript/nodes/subobjects/citation.py, src/cript/nodes/subobjects/computational_forcefield.py, src/cript/nodes/subobjects/condition.py, src/cript/nodes/subobjects/equipment.py, src/cript/nodes/subobjects/ingredient.py, src/cript/nodes/subobjects/parameter.py, src/cript/nodes/subobjects/property.py, src/cript/nodes/subobjects/quantity.py, src/cript/nodes/supporting_nodes/file.py
added vocabulary links to documentation of where users can get the vocab for each attribute.
If I could make the site url a variable and refer to it instead of having to hardcode it, then that would be the best because I could just change the domain to production and I am simply done. But I could not figure that out.
`mkdocs.yaml`
```yaml
site_domain: https://mycriptapp.org
```
`docstring`
```
[my link]({{ site_domain}}/about/)
```
I tried Jinja, [macro plugin](https://mkdocs-macros-plugin.readthedocs.io/en/latest/) but I was not able to get it to work
I ended up [leaving a question on mkdocs discussion board](https://github.com/squidfunk/mkdocs-material/discussions/5775) for now and will hopefully get an answer soon.
Looked through stackoverflow and found no answers
=> added vocabulary links to all nodes in documentation

docs/api/controlled_vocabulary_categories.md, src/cript/__init__.py, src/cript/api/__init__.py, src/cript/api/api.py, src/cript/api/vocabulary_categories.py, src/cript/nodes/util/material_deserialization.py, tests/api/test_api.py
I think the enum class name of `ControlledVocabularyCategories` is just too long and makes the code look less clean I think. I think if we change it to a shorter like `VocabCategories` it will still create the same meaning for the user and keep the code clean and concise.
* changed documentation in controlled_vocabulary_categories.md
* changed example documentation
* changed how it is imported into __init__.py
* changed the test_api.py for it
* changed how it is used in api.py
* changed how it is used in material_deserialization.py
I think for the most accurate results, we would have to ask users about it what they thought and if they liked it we keep it, otherwise we remove it. I think this is something that is large and I am guessing users will either want it shorter or will not miss it …
=> refactor enum name from `ControlledVocabularyCategories` to `VocabCategories`

src/cript/api/api.py
adding `None` in header escapes the html and looks weird on the right side navigation
* removed back ticks from `None` in the header
<details>
<summary>click to see changes</summary>
</details>
=> API documentation side navigation is fixed

tests/api/test_api.py
changed `test_api_search_uuid` to be dynamic for all server environments
* changed UUID test from being static, which broke when testing different servers, to be dynamic and using the `exact_name search` withing `UUID search`
=> Change api UUID search test to work with any server instance

tests/conftest.py
changed cognito variables for API in tests to point to staging storage
* changed conftest to override production API object class variables
* spaced out code a bit to be easier to read
=> Pointing file upload tests to staging AWS S3 storage

src/cript/api/api.py
gives slightly better error if the user is out of USA
```bash
try:
return complexjson.loads(self.text, **kwargs)
except JSONDecodeError as e:
>           raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
E           requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
..\..\venv\lib\site-packages\requests\models.py:975: JSONDecodeError
```
> this error is because when the API is pinged from outside of USA it returns a text of `"You must be in the US to access Cript app."` and since this is not JSON it gives a bad JSON deserialization error
After raising error from requests, the error becomes
```bash
if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: …
```
=> raising error for getting db schema via requests

docs/examples/simulation.md, docs/examples/synthesis.md, src/cript/nodes/primary_nodes/collection.py, src/cript/nodes/primary_nodes/computation_process.py, src/cript/nodes/primary_nodes/inventory.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/process.py, src/cript/nodes/primary_nodes/project.py, src/cript/nodes/subobjects/ingredient.py, src/cript/nodes/subobjects/property.py, src/cript/nodes/supporting_nodes/file.py, src/cript/nodes/util/__init__.py, src/cript/nodes/util/material_deserialization.py, tests/fixtures/primary_nodes.py, tests/nodes/primary_nodes/test_inventory.py, tests/nodes/primary_nodes/test_material.py, tests/nodes/primary_nodes/test_process.py, tests/nodes/supporting_nodes/test_file.py, tests/test_node_util.py
One of the users made a comment that every other attribute on a node is singular except for identifiers which is plural and it would be more intuitive if it was singular
* changed all files, tests, and documentation to use `identifier` instead of `identifiers`
* all tests are passing
* fixed any broken links for vocabulary within documentation
* removed unneeded test for test_file.py
* all tests are passing after heavy refactoring
=> Refactor/Renamed material `identifiers` to `identifier`

src/cript/nodes/supporting_nodes/file.py
I checked through the rest of the attributes table and it seems like for the most part they are already done. 
File notes was the only thing that seems to be missing in its attributes table.
I wonder if users would know how to use the notes attribute or know where to find the docs on it or do we need more documentation guiding them through that?
=> updated file node doc with notes

src/cript/nodes/supporting_nodes/file.py
added `name` to file node docs attributes table and JSON representation as it is a required attribute and was missing previously
=> added `name` to file node docs attributes table

src/cript/api/api_config.py, tests/api/test_api.py
fixed bigsmiles search test
* fixed SearchMode from `BIG_SMILES` to `BIGSMILES`
* after refactoring the SearchMode from `BIG_SMILES` to `BIGSMILES` this was left out, but it is now tested and working
* changed timeout from `25` to `120`
* the API takes a really long time to send response for bigsmiles search and waiting 2 minutes before quitting could be a good boundary for now
* if we realize that it is too small we can raise it again
tests are working!
=> fixed `BIGSMILES` search test

.github/workflows/test_coverage.yaml
lowering coverage CI to `85%` because it does not account for integration tests
=> lowering coverage CI because it does not account for integration tests

src/cript/api/paginator.py
if there is an issue while converting the API response to JSON, then I am assuming that there has been an error and the server has returned something that was not JSON (e.g. text) where JSON was expected, so there must be an error, thus raise the error to the user.
Before this change, the user would get a `JSONDecodeError`, which made no sense for them and is not pointing out the error very well, but with this the error becomes a bit better for the user to know what happened.
```
self = <Response [403]>, kwargs = {}
def json(self, **kwargs):
r"""Returns the json-encoded content of a response, if any.
:param \*\*kwargs: Optional arguments that ``json.loads`` takes.
:raises requests.exceptions.JSONDecodeError: If the response body does not
contain valid json.
"""
if not self.encoding and …
```
=> upgrade paginator error handling for response JSON conversion

src/cript/api/api.py, src/cript/api/exceptions.py, src/cript/api/paginator.py, tests/api/test_api.py, tests/integration_test_helper.py, tests/nodes/primary_nodes/test_collection.py, tests/nodes/primary_nodes/test_computation.py, tests/nodes/primary_nodes/test_computational_process.py, tests/nodes/primary_nodes/test_data.py, tests/nodes/primary_nodes/test_experiment.py, tests/nodes/primary_nodes/test_inventory.py, tests/nodes/primary_nodes/test_material.py, tests/nodes/primary_nodes/test_process.py, tests/nodes/primary_nodes/test_project.py, tests/nodes/primary_nodes/test_reference.py, tests/nodes/subobjects/test_algorithm.py, tests/nodes/subobjects/test_citation.py, tests/nodes/subobjects/test_computational_forcefiled.py, tests/nodes/subobjects/test_condition.py, tests/nodes/subobjects/test_equipment.py, tests/nodes/subobjects/test_ingredient.py, tests/nodes/subobjects/test_parameter.py, tests/nodes/subobjects/test_property.py, tests/nodes/subobjects/test_quantity.py, tests/nodes/subobjects/test_software.py, tests/nodes/subobjects/test_software_configuration.py, tests/nodes/supporting_nodes/test_file.py
giving users a way to delete a nodes from the API
* wrote `cript.API.delete()` method
* wrote integration tests for delete
* wrote full documentation for delete
---
* created a `set_log()` method
* it essentially sets the logger for the whole `cript.API` class
* was considering making it into a getter that would create a new logger and return it, but since each class should only have one logger that might encourage bad programming and create bugs
* made `verbose` into a property that changes the class logger after the user sets it.
* The user simply sets it casually and we rearrange the logger behind the scenes for them to work correctly so they can turn verbose `ON` and `OFF` easily throughout their script 
* The logger has good simple logic so we don't have to keep putting `if …
=> Feature:  HTTP `DELETE` node

tests/nodes/subobjects/test_software_configuration.py
Before I was expecting `software_configuration` to not be allowed to be deleted in `delete integeation tests`, but that is not the case, and `software_configuration` should be allowed to be deleted, `software` should not be deleted. 
Updated `delete` `software_configuration` test to expect deletion
Credit to @InnocentBug for helping me understand and figure that part out
=> Updated delete `software_configuration` integration test to expect deletion and not an API error

src/cript/nodes/primary_nodes/data.py
updated documentation for `Data` node
* updated attributes table
* added docstrings to constructor
* added example data instantiation code
* attribute tables are updated manually and prone to errors
=> updated `Data` documentation

src/cript/nodes/core.py
catching generic python exception and raising better exception for when users specify too many arguments in their constructors.
=> fix catching the right exceptions

src/cript/nodes/primary_nodes/data.py
Moving the example code for creating `Data` node above the `Parameter` and `Returns` section in under the constructor
* the ordering between all the nodes I think is inconsistent because each one is in a different order
* this would not change the overall documentation, its usefulness, but lessens its perfection
* the ordering goes against [Numpy style guide ideal order](https://github.com/C-Accel-CRIPT/Python-SDK/wiki/Documentation#numpy-style-docstring-ideal-order), but I think it is okay because
1. we are not currently following the ideal order anywhere else
2. it looks nicer and has better UI/UX for the user
=> Docs: putting `Data` node example code above

src/cript/api/api.py
The user is often unsure if the SDK uploaded their file to AWS S3 or not, so I added a log to the terminal that tells the user when their file was uploaded to S3.
* added a log after upload to s3
The output looks like this
* the terminal output is a bit too long, but I was unsure of how else to write it
=> added log for file uploads

src/cript/api/api.py
instead of using backticks ` I am now using single quotes. I think that is much more standard and cleaner. It was bothering me that I wrote it previously and the logs were not as standard and clean as they could be.
=> changed log message for delete

.github/workflows/build_and_deploy_docs.yaml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/docs_check.yaml, .github/workflows/mypy.yaml, .github/workflows/test_coverage.yaml, .github/workflows/test_examples.yml, .github/workflows/tests.yml, .github/workflows/trunk.yml, requirements.txt, requirements_dev.txt, setup.cfg
Previously, we forgot to setup the python version for our CI tests.
I resolved this, which made python 3.7 build to correctly fail.
1. Fixed the tests to correctly setup python.
2. Added permissions to workflows
3. Changed the confusing name of the trunk test.
I had to change the version of packages to ranges instead of fixed values.
Otherwise it is impossible to get 3.7 and 3.11 builds to pass at the same time.
=> Enforce correct python version for testing.

tests/fixtures/supporting_nodes.py
created `complex_local_file_node` fixture for easy testing for future
* added `notes` attribute to already existing `complex_file_node`
* added `complex_local_file_node` fixture
* this comes in handy during integration tests or during tests where we want to swap out the file node really quickly to see if the issue is the file node having a local source or a web source
=> created `complex_local_file_node` fixture for easy testing for future

tests/api/test_api.py
uncommented test and changed test name to be self documenting
* uncommented `test_create_api` to allow it to be usable again
* not a hugely important test, but we already have it so we can use it
* if we need to eliminate tests later to lighten up maintenance, this can be a great place to remove because the API client is test throughout the SDK anyways
* renamed functional test from `test_api_cript_env_vars` to `test_create_api_with_none`
=> API Tests: rename test & delete test

setup.cfg
updated SDK version from `2.0.0` to `2.1.0`
* updated SDK version from `2.0.0` to `2.1.0` 
* Before each release we have to increment the package version manually
* This workflow is very problematic because there has ben Many times where I have forgotten to change the version number before a release
* This needs to be automated to reduce chances of errors
* @InnocentBug if you have any ideas please feel free to let me know
Python SDK 2.1.0 will be the last version that will support Python 3.7. All next versions of Python SDK will support Python 3.8 or higher as [Python 3.7 has reached end of life](https://devguide.python.org/versions/)
=> updated SDK version from `2.0.0` to `2.1.0`

tests/api/test_api.py
switch `test_config_file` test to use staging host instead of develop
develop server seems to not be stable, so moving every host to staging
=> switch `test_config_file` to use staging for `host` instead of develop

src/cript/api/api.py, src/cript/api/valid_search_modes.py, src/cript/nodes/util/__init__.py
updated documentation on working with `cript.API.search`, `paginator`, and `deserializing JSON to nodes`
* added link at end of valid_search_modes.py to cript.API.search()
* added documentation for deserialization of JSON to node to API.search
* collapsed `cript.API.search` code examples to be easier and more compact
* copied over code example from `load_nodes_from_json` documentation to cript.API.search to make working with search documentation easier.
* added links to `Paginator` and `load_nodes_from_json` in notes of `cript.API.search` for user to easily flip to those pages
> SearchModes link additions
---
> JSON to node code examples
---
> slightly changed code example to be more understandable
We can merge this into SDK before or after release of v2.1.0
=> Upgrade documentation

.github/workflows/build_and_deploy_docs.yaml
* Giving GitHub workflow the permission to read from `main` and write to `gh-pages`
* GitHub actions kept getting `permission denied errors` when trying to write to `gh-pages` branch, and the issue was that we did not specify that it has write permissions.
=> Fix MKDocs Build Workflow Permissions

requirements_docs.txt
Upgrade requirements_docs.txt
requirements_dev.txt needed upgrades, but not sure if we want to change our syntax from `>=` to `==`
---
* mkdocs 9.3 dropped support for Python 3.7
* pymdown-extensions 10.3 dropped support for Python 3.7
=> Upgrade `requirements_docs.txt`

src/cript/api/exceptions.py
clean up `APIError` so it is uniform everywhere and clean
removed unnecessary code since it is being used uniformly everywhere
=> clean up `APIError` so it is uniform everywhere and clean

mkdocs.yml, requirements_docs.txt
fixed hot reload issue with MKDocs and upgraded outdated packages
* `mkdocstrings` removed `watch` feature in `0.23.0` because MKDocs does it natively now
* changed MKDocs to reflect the change
* this was the issue that I bumped into previously and tried to temporarily address with this PR: https://github.com/C-Accel-CRIPT/Python-SDK/pull/354
* Found a better and more permanent solution
* upgraded some packages that recently came out
=> using MKDocs native `watch` feature and upgraded `requirements_docs.txt`

src/cript/api/api.py
wrote new API method `delete_node_by_uuid`
* wrote new API method, `delete_node_by_uuid`
* wrote documentation for `delete_node_by_uuid`
* changed `api.delete()` to call `delete_node_by_uuid` under the hood
* updated `api.delete` documentation
<details>
<summary>click to see `cript.API` documentation with new changes</summary>
</details>
* ran integration tests and it is working fine
=> Feature: created `API.delete_node_by_uuid(node_type, node_uuid)` 

src/cript/api/api.py, tests/api/test_api.py, tests/conftest.py, tests/fixtures/api_fixtures.py
Sarah asked for a method that the user can get a node via UUID like the past SDK had `api.get("uuid string")`, so I made `cript.API.get_node_by_uuid` it is not exactly the same because it requires UUID and the node you are looking for, as required by the API, but I think it will make SDK scripts easier to write and be more helpful
* GtiHub: https://github.com/C-Accel-CRIPT/Python-SDK/issues/325
* Trello: https://trello.com/c/BgvWn0cQ
* wrote test for `get_node_by_uuid`
* wrote documentation for `get_node_by_uuid`
* `test_api_search_get_node_by_uuid` test is passing successfully
* wrote `sodium_polystyrene_uuid` api fixture
* made `test_api_search_get_node_by_uuid` DRY with uuid fixture
* instead of repeating the same EXACT_NAME search everywhere in the tests any time we need a UUID
* I …
=> Feature: `cript.API.get_node_by_uuid(uuid)`

tests/api/test_api.py, tests/fixtures/api_fixtures.py
Upgrade API UUID tests to use dynamic UUID fixtures 
* changed material fixture to be more abstract and more flexible
* if we want to add more data to the fixture, we can just add it to the dictionary and all current tests will run fine.
* changed past tests to work with the new dynamic UUID fixture cleanly
=> Upgrade API UUID tests to use dynamic UUID fixtures 

src/cript/nodes/subobjects/algorithm.py, tests/nodes/subobjects/test_software_configuration.py
Fixed software configuration commented out test. Simplified the test and it works easier and better
* test works and runs fine
* found some empty links within algorithm.py and fixed them pointing to the correct page of the vocabulary
=> Fixed software configuration commented out test

docs/examples/simulation.md, src/cript/nodes/supporting_nodes/file.py, tests/nodes/supporting_nodes/test_file.py
* requiring file extension for all nodes when created
* updated documentation
* updated File node creation example code
* changed the code examples from minimal and maximal to 2 maximal file nodes with local path source and web url source
* fixed `ensure_uploaded` documentation
* the syntax was wrong
* fixed example code documentation after the error popped up
> **really happy that there is automated tests that check the validity of the code** 
* formatted entire example code walkthrough and comments
<details>
<summary> click to see updated file documentation </summary>
</details>
<details>
<summary> click to see formatted code example documentation </summary>
</details>
=> Require file extension for `cript.File` node

.github/workflows/mypy.yaml, .github/workflows/test_coverage.yaml, .github/workflows/test_examples.yml, .github/workflows/tests.yml
[Python 3.12](https://www.python.org/downloads/release/python-3120/) was released 10/2/2023 and I am adding it to our CI to use 3.12 because it has new feature, it ensures compatibility, and it is faster than 3.11
=> Change Python 3.11 to 3.12 in GitHub Workflows

src/cript/nodes/primary_nodes/reference.py
reference documentation had an extra space between the words, which was weird, so I changed that and it looks nice now. 
> Screenshots below
=> fixed reference docs formatting

src/cript/nodes/primary_nodes/material.py
removed redundant material name getter and setter. Name attribute is not needed because it already exists in primary base node
=> removed redundant Material name getter and setter

src/cript/nodes/util/__init__.py, tests/nodes/test_utils.py
`load_nodes_from_json` works with both str and dict args
this makes the function a more versatile and makes user scripts easier to write since they don't have to change formats.
The code written for it is pretty clean and nice to work with I think.
* `load_nodes_from_json` accepts with JSON str or dict arguments
* wrote a small test for `load_nodes_from_json` using a JSON dict argument
=> `load_nodes_from_json` works with both str and dict args

src/cript/api/exceptions.py
added documentation to `CRIPTDuplicateNameError`
=> wrote documentation for `CRIPTDuplicateNameError` exception & improved error message

src/cript/api/api.py, src/cript/nodes/core.py, tests/api/test_api.py
As discussed with @bearmit 
A flag that disables partially the tests is being implemented.
At the moment we do not disable tests by default.
There is a text output that let's users know that they can disable the validation if needed.
Some checks are forced even as tests are disabled.
- upon `save`
- and upon `node.json`
I changed the logging  text to let users know that they can disable the validation.
And marked forced checks as such, letting the user know that they can't be disabled and that if they have issues, they should enable the tests.
I added a test that checks, that a wrong node is accepted if tests are disabled, but detected if forced.
None.
If we decide to disable tests by default, we just have to change the default value for `cript.API.skip_validation` to `True`.
=> Skip validation

.trunk/configs/.cspell.json, src/cript/nodes/core.py, tests/test_node_util.py
The SDK can produce fully self-contained JSON string for node graphs.
Such a node graph does not contain any UUID reference (self-contained) and can be super helpful for users if they want to store their work in a JSON file  before uploading it to CRIPT.
@bearmit expressed that he would like this feature.
Also added a hint about using `kwargs` to beautify JSON strings into the documentation.
A test is included to ensures that self-containing JSON can be parsed by `cript.load_nodes_from_json`.
=> Self-Contained JSON file format

src/cript/nodes/core.py
wrote documentation for `Base.find_children()`
* wrote docs
* added numpy documentation sections
* wrote documentation for the attributes, return type, and notes
* wrote clear example code that supports doctest
* added type hinting where needed
The documentation is a bit long, but I don't know how to make it shorter without making it harder to understand. I think it might be okay for now.
=> Docs for find children method

src/cript/nodes/core.py
Updating just the docs, not a release to Pypi
* wrote docs for `find_children` Base method
* added type hinting to `Base.find_childre()`
* added return type
* wrote clear example with doctest
* upgraded notes section to be easier to read and understand
=> Docs Update

docs/examples/synthesis.md, src/cript/api/data_schema.py, src/cript/nodes/primary_nodes/collection.py, src/cript/nodes/primary_nodes/computation.py, src/cript/nodes/primary_nodes/computation_process.py, src/cript/nodes/primary_nodes/data.py, src/cript/nodes/primary_nodes/experiment.py, src/cript/nodes/primary_nodes/inventory.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/project.py, src/cript/nodes/primary_nodes/reference.py, src/cript/nodes/subobjects/algorithm.py, src/cript/nodes/subobjects/citation.py, src/cript/nodes/subobjects/computational_forcefield.py, src/cript/nodes/subobjects/condition.py, src/cript/nodes/subobjects/equipment.py, src/cript/nodes/subobjects/ingredient.py, src/cript/nodes/subobjects/parameter.py, src/cript/nodes/subobjects/property.py, src/cript/nodes/subobjects/quantity.py, src/cript/nodes/subobjects/software.py, src/cript/nodes/subobjects/software_configuration.py, src/cript/nodes/supporting_nodes/file.py, src/cript/nodes/supporting_nodes/user.py, tests/nodes/primary_nodes/test_material.py
Some nodes didn't trigger self validation in the constructor.
This is fixed now.
All nodes only update their JSON attributes if they are valid, even in the constructor.
None yet.
=> Bugfix auto validate

docs/faq.md, src/cript/api/api.py, src/cript/api/paginator.py, tests/api/test_search.py
Before there was no path to recovery if an API search was returning nodes that were deemed incorrect by the SDK.
Now, there is a way to disable auto node conversion.
I think this should only be last resort to recover for advanced users.
But I included an FAQ to explain it to users.
=> Allow users to handle invalid nodes coming from a search against the API

.trunk/configs/.cspell.json, src/cript/nodes/core.py, src/cript/nodes/exceptions.py, src/cript/nodes/primary_nodes/project.py, src/cript/nodes/util/__init__.py, src/cript/nodes/util/core.py, src/cript/nodes/util/json.py, src/cript/nodes/uuid_base.py, tests/api/test_search.py, tests/test_node_util.py
Now the node UUID cache actually works as intended.
Users can only have one python object with the same UUID.
Added a functionality that allows you to circumvent this cache explictly.
This should be a feature that users don't really use.
=> Fix problems with the node cache

src/cript/nodes/core.py, src/cript/nodes/primary_nodes/collection.py, src/cript/nodes/primary_nodes/computation.py, src/cript/nodes/primary_nodes/computation_process.py, src/cript/nodes/primary_nodes/data.py, src/cript/nodes/primary_nodes/experiment.py, src/cript/nodes/primary_nodes/inventory.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/process.py, src/cript/nodes/primary_nodes/project.py, src/cript/nodes/subobjects/algorithm.py, src/cript/nodes/subobjects/citation.py, src/cript/nodes/subobjects/computational_forcefield.py, src/cript/nodes/subobjects/condition.py, src/cript/nodes/subobjects/equipment.py, src/cript/nodes/subobjects/ingredient.py, src/cript/nodes/subobjects/property.py, src/cript/nodes/subobjects/software_configuration.py, src/cript/nodes/util/core.py, src/cript/nodes/util/json.py, tests/fixtures/primary_nodes.py, tests/test_node_util.py
Some JSON with cycles broken by UID couldn't be deserialized because the order of UID was not good for the JSON module.
Store a temporary UIDProxy element if a UID can't be resolved.
After reading in with `load_nodes_from_json` the proxies are replaced by the nodes if possible.
The type declaration was fixed to nodes before, now UIDProxy objects are permissible.
For the implementation of the Node type hint that is equivalent to `Union[Node, UIDProxy]` internal implementations of the `typing` module are used.
=> Fix uid cycle deserialization

src/cript/nodes/core.py, src/cript/nodes/node_iterator.py, src/cript/nodes/primary_nodes/collection.py, src/cript/nodes/primary_nodes/computation.py, src/cript/nodes/primary_nodes/computation_process.py, src/cript/nodes/primary_nodes/data.py, src/cript/nodes/primary_nodes/experiment.py, src/cript/nodes/primary_nodes/inventory.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/process.py, src/cript/nodes/primary_nodes/project.py, src/cript/nodes/subobjects/algorithm.py, src/cript/nodes/subobjects/citation.py, src/cript/nodes/subobjects/computational_forcefield.py, src/cript/nodes/subobjects/condition.py, src/cript/nodes/subobjects/equipment.py, src/cript/nodes/subobjects/ingredient.py, src/cript/nodes/subobjects/property.py, src/cript/nodes/subobjects/software_configuration.py, src/cript/nodes/util/core.py, src/cript/nodes/util/json.py, src/cript/nodes/uuid_base.py, tests/fixtures/primary_nodes.py, tests/test_node_util.py
Add iterator capability for UUID nodes.
UUID attributes are strictly strings now.
Let's add some test to ensure iteration over nodes is dfs, and we need to tests this with a graph that contains cycles.
- [ x] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.
- [ x] I have updated the documentation to reflect my changes.
- [ x] My code changes have been verified by automated tests and pass all relevant test scenarios.
=> Add iterators for UUID nodes

src/cript/api/api.py, src/cript/exceptions.py, src/cript/nodes/exceptions.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/project.py, src/cript/nodes/util/core.py, tests/test_node_util.py
This changes the previous errors into warnings.
We use still custom classes to issue the warnings, this enables users to convert them into Exceptions if desired.
This can help to handle the warnings if desired.
None
=> Error to warning

.github/workflows/tests.yml, README.md, setup.cfg, src/cript/api/api.py, src/cript/api/paginator.py, src/cript/nodes/core.py, src/cript/nodes/primary_nodes/computation_process.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/process.py, src/cript/nodes/subobjects/property.py, tests/api/test_search.py, tests/fixtures/api_fixtures.py, tests/fixtures/primary_nodes.py, tests/fixtures/subobjects.py, tests/fixtures/supporting_nodes.py, tests/nodes/primary_nodes/test_material.py, tests/nodes/subobjects/test_property.py, tests/nodes/test_utils.py, tests/test_node_util.py
Updated search URL generation.
It now works with 
Some updates to the paginator interface that enables partial searches, that allows interrupted searches for the SDK as well.
Many entries on `stage` are invalid.
So we had to work around this in the tests.
Ideally we don't have to do that.
@brili 
I noticed, that BigSMILES search does not deliver 10 nodes by default. It is 1 node for me.
@brili 
Also it appears that the `after` method returns some nodes multiple times.
I get the same UUID in the search results, I don't think that is as it should be.
=> Update search, so it works with the new `after` syntax.

.github/workflows/tests.yml, .trunk/configs/.cspell.json, CHANGELOG.md, README.md, setup.cfg, src/cript/api/api.py, src/cript/api/paginator.py, src/cript/exceptions.py, src/cript/nodes/core.py, src/cript/nodes/exceptions.py, src/cript/nodes/primary_nodes/computation_process.py, src/cript/nodes/primary_nodes/material.py, src/cript/nodes/primary_nodes/process.py, src/cript/nodes/primary_nodes/project.py, src/cript/nodes/subobjects/property.py, src/cript/nodes/util/core.py, tests/api/test_search.py, tests/fixtures/api_fixtures.py, tests/fixtures/primary_nodes.py, tests/fixtures/subobjects.py, tests/fixtures/supporting_nodes.py, tests/nodes/primary_nodes/test_material.py, tests/nodes/subobjects/test_property.py, tests/nodes/test_utils.py, tests/test_node_util.py
- `cript.API` searches work as intended.
- SDK initiated searches can be controlled and interrupted for large queries.
- Saving projects is not supported. Temporarily, you can use `get_expanded_json` to store a JSON representation of projects, which can be uploaded into CRIPT at a later time.
- Permission settings in CRIPT do not influence the behavior of the SDK objects.
- Tests that require valid tokens (like saving or searching) are not included in CI/CD tests.
- BigSMILES searches can contain duplicates.
- Search is now matched with the API requirements.
- The Paginator interface changed to reflect the backend requirements.
````shell
=============================================================================================== test session starts …
```
=> Release 2.4.0
